{{ if not .Values.services.cache.external }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cache-config
data:
  redis-config: |
    maxmemory 1gb
    maxmemory-policy volatile-lru
{{ end }}
