apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-release-server-config
data:
  FILE_STORE_ENDPOINT: {{ .Release.Name }}-filestore-service
  FILE_STORE_PORT: {{ .Values.filestore.port | quote}}
  FILE_STORE_BUCKET: {{ .Values.filestore.bucket }}
  FILE_STORE_REGION: {{ .Values.filestore.region }}
  FILE_STORE_USE_SSL: {{ .Values.filestore.useSsl | quote}}
  {{ if .Values.certmanager.enabled }}
  WEB_API_BASE_URL: https://{{ .Values.ingress.hosts.webApiHost }}
  RELEASE_SERVER_BASE_URL: https://{{ .Values.ingress.hosts.releaseServerHost }}
  {{ else }}
  WEB_API_BASE_URL: http://{{ .Values.ingress.hosts.webApiHost }}
  RELEASE_SERVER_BASE_URL: http://{{ .Values.ingress.hosts.releaseServerHost }}
  {{ end }}
  
