apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-api-config
data:
  APPLICATION_NAME: {{ .Values.webApi.applicationName }}
  APPLICATION_LICENSE_KEY: {{ .Values.webApi.serverLicenseKey }}
  FORCEHTTPS: "false"
  PORT: "5000"
  {{ if .Values.certmanager.enabled }}
  JWT_AUDIENCE: https://{{ .Values.ingress.hosts.webApiHost }}
  {{ else }}
  JWT_AUDIENCE: http://{{ .Values.ingress.hosts.webApiHost }}
  {{ end }}
  REDIS_URL: redis://{{ .Release.Name }}-cache-service:6379
  GOOGLE_CLIENT_ID: {{ .Values.sso.google.clientId | quote }}
  IPRATELIMITOPTIONS_IPWHITELIST: {{ .Values.webApi.ipRateLimitOptions.ipWhitelist | toJson | quote }}
  IPRATELIMITOPTIONS_GENERALRULES_0_LIMIT: {{ .Values.webApi.ipRateLimitOptions.rateLimit | quote }}
  {{ if .Values.services.geoip.external }}
  GEOIPSERVER_URL: {{ .Values.geoip.serverUrl | quote }}
  GEOIPSERVER_APIKEY: {{ .Values.geoip.apiKey | quote }}
  {{ else }}
  GEOIPSERVER_URL: http://{{ .Release.Name }}-geoip-service:8080/json
  {{ end }}
  # Mail settings
  EMAIL_FROMADDRESS: {{ .Values.webApi.email.fromAddress }}
  EMAIL_FROMNAME: {{ .Values.webApi.email.fromName }}
  EMAIL_SIGNATURE: {{ .Values.webApi.email.signature }}
  SMTP_HOST: {{ .Values.webApi.email.smtp.host | quote }}
  SMTP_PORT: {{ .Values.webApi.email.smtp.port | quote}}
  SMTP_ENABLESSL: {{ .Values.webApi.email.smtp.enableSsl | quote}}
  MAILGUN_DOMAIN: {{ .Values.webApi.email.mailgun.domain | quote }}
  MAILGUN_APIKEY: {{ .Values.webApi.email.mailgun.apiKey | quote }}
  SENDGRID_APIKEY: {{ .Values.webApi.email.sendgrid.apiKey | quote }}

  # Error monitoring
  BUGSNAG_APIKEY: {{ .Values.webApi.bugsnag.apiKey | quote }}

  # App metrics
  NEW_RELIC_LICENSE_KEY: {{ .Values.webApi.newRelic.licenseKey | quote }}
  NEW_RELIC_APP_NAME: {{ .Values.webApi.newRelic.applicationName | quote }}
