{{ range .Values.ingress.hosts.webApiHosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-web-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "api.cryptlex.com"
    {{ if $.Values.certmanager.issuer.production }}
    cert-manager.io/issuer: {{ $.Release.Name }}-letsencrypt-production
    {{ else}}
    cert-manager.io/issuer: {{ $.Release.Name }}-letsencrypt-staging
    {{ end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ . }}
      secretName: {{ printf "%s%s%s" $.Release.Name . | sha256sum | trunc 30}}-tls-secret
  rules:
    - host: {{ . }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-web-api-external-service
                port: 
                  number: 443
            pathType: ImplementationSpecific 
{{ end }}