---
language: python

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.14.3-linux-amd64.tar.gz
    - TARGET_BR=gh-pages
    - REPO_DIR=/home/travis/build/cryptlex/helm-charts
    - GH_URL=https://cryptlex.github.io/helm-charts

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

script:
  # Check charts format
  - >
     for dir in `ls ${REPO_DIR}/cryptlex`; do
      helm lint ${REPO_DIR}/cryptlex/$dir
      if [ $? != 0 ]; then
       travis_terminate 1
      fi
     done
  - >
    if [ $TRAVIS_BRANCH = 'master' ] ; then
      # Temporary dir for storing new packaged charts and index files
      BUILD_DIR=$(mktemp -d)

      # Useful URLs
      REPO_URL=`git config remote.origin.url`
      SHA=`git rev-parse --verify HEAD`

      # Push temporary directory to the stack
      pushd $BUILD_DIR

      # Iterate over all charts are package them
      for dir in `ls ${REPO_DIR}/cryptlex`; do
       helm dep update ${REPO_DIR}/cryptlex/$dir
       helm package ${REPO_DIR}/cryptlex/$dir
      done

      # Pop temporary directory from the stack
      popd

      # List all the contents that we will push
      ls ${BUILD_DIR}

      # Clone repository and empty target branch
      git clone ${REPO_URL} out
      cd out
      git checkout ${TARGET_BR} || git checkout --orphan ${TARGET_BR}
      cd ..
      # rm -rf out/* || exit 0

      # Copying contents of BUILD_DIR to out folder
      cp $BUILD_DIR/* out/
      cd out

      # Indexing of charts
      if [ -f index.yaml ]; then
       helm repo index --url ${GH_URL} --merge index.yaml .
      else
       helm repo index --url ${GH_URL} .
      fi

      # Deploy if there are some changes
      git diff --quiet
      if [ $? != 0 ]; then
       # Add all new files to staging phase and commit the changes
       git config user.name "Travis CI"
       git config user.email "travis@travis-ci.org"
       git add *.yaml *.tgz .
       git status
       git commit -m "Travis deploy ${SHA}"
       # We can push.
       git remote add origin-pages https://${GITHUB_TOKEN}@github.com/cryptlex/helm-charts.git > /dev/null 2>&1
       git push --quiet --set-upstream origin-pages gh-pages 
       git push
      fi
    fi
