apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}