apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-portals-secret
type: Opaque
stringData:
{{ if .Values.webPortals.customDomainAccessToken }}
  CUSTOM_DOMAIN_ACCESS_TOKEN: {{ .Values.webPortals.customDomainAccessToken  | quote }}
{{ end }}