apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-api-secret
type: Opaque
stringData:
  {{ if .Values.services.database.external }}
  DATABASE_URL: {{ .Values.webApi.databaseUrl }}
  {{ else }}
  DATABASE_URL: postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Release.Name }}-database-service:5432/{{ .Values.database.name }}
  {{ end }}
  RSA_PASSPHRASE: {{ .Values.webApi.rsaPassphrase }}
  JWT_RSA_PRIVATEKEY: {{ .Values.webApi.jwtRsaPrivateKey | quote }}
  JWT_RSA_PUBLICKEY: {{ .Values.webApi.jwtRsaPublicKey | quote }}
  SMTP_USERNAME: {{ .Values.webApi.email.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.webApi.email.smtp.password | quote }}
