{{ if not .Values.services.database.external }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Release.Name }}-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/database-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: database
          image: postgres:10.7-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-database-secret
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.db }}
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       key: POSTGRES_USER
            #       name: {{ .Release.Name }}-database-secret
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       key: POSTGRES_PASSWORD
            #       name: {{ .Release.Name }}-database-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-volume
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pv-claim
{{ end }}
