{{ if and .Values.services.filestore.enabled (not .Values.services.filestore.external) }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-filestore
  labels:
    app: {{ .Release.Name }}-filestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-filestore
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-filestore
    spec:
      volumes:
        - name: filestore-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pv-claim
      containers:
        - name: filestore
          image: minio/minio:RELEASE.2019-08-29T00-25-01Z
          imagePullPolicy: "IfNotPresent"
          args:
            - server
            - /data
          ports:
            - containerPort: {{ .Values.filestore.port }}
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: FILE_STORE_SECRET_KEY
                  name: {{ .Release.Name }}-filestore-secret
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: FILE_STORE_ACCESS_KEY
                  name: {{ .Release.Name }}-filestore-secret
          volumeMounts:
            - mountPath: /data
              name: filestore-volume
{{ end }}