{{ if .Values.services.filestore.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-release-server
  labels:
    app: {{ .Release.Name }}-release-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-release-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-release-server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-maps/release-server-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/filestore-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: release-server
          image: cryptlex/cryptlex-release-server:3.2.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-release-server-config
            - secretRef:
                name: {{ .Release.Name }}-filestore-secret
          # env:
          #   - name: FILE_STORE_SECRET_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         key: FILE_STORE_SECRET_KEY
          #         name: {{ .Release.Name }}-filestore-secret
          #   - name: FILE_STORE_ACCESS_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         key: FILE_STORE_ACCESS_KEY
          #         name: {{ .Release.Name }}-filestore-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
{{ end }}