{{ if not .Values.services.database.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-pv-claim
spec:
  storageClassName: {{ .Values.services.database.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.database.storage }}
{{ end }}