{{ if not .Values.services.database.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-pv-claim
spec:
  {{ if .Values.services.database.storageClass }}
  storageClassName: {{ .Values.services.database.storageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.database.storage }}
{{ end }}