{{ if and .Values.services.filestore.enabled (not .Values.services.filestore.external) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-filestore-pv-claim
spec:
  {{ if not (eq .Values.services.filestore.storageClass "default") }}
  storageClassName: {{ .Values.services.filestore.storageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.filestore.storage }}
{{ end }}