{{ if and .Values.services.rabbitMq.enabled (not .Values.services.rabbitMq.external) }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  image: masstransit/rabbitmq:3.9.15
  replicas: {{ .Values.rabbitMq.replicaCount }}
  resources:
    requests:
      cpu: 200m
      memory: "500Mi"
    limits:
      cpu: 1000m
      memory: "1Gi"
  rabbitmq:
    additionalPlugins:
      - rabbitmq_delayed_message_exchange
    additionalConfig: |
      default_user = {{ .Values.rabbitMq.username }}
      default_pass = {{ .Values.rabbitMq.password }}
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storage: {{ .Values.services.rabbitMq.storage }}
{{ end }}