{{ if not .Values.services.database.external }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Release.Name }}-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/database-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: database
          image: "{{ .Values.services.database.image.repository }}:{{ .Values.services.database.image.tag }}"
          imagePullPolicy: {{ .Values.services.database.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-database-secret
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.db }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-volume
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-database-pv-claim
{{ end }}
