{{ if and .Values.services.filestore.enabled (not .Values.services.filestore.external) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-filestore
  labels:
    app: {{ .Release.Name }}-filestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-filestore
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-filestore
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/filestore-secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: filestore-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-filestore-pv-claim
      containers:
        - name: filestore
          image: minio/minio:RELEASE.2020-05-16T01-33-21Z
          imagePullPolicy: "IfNotPresent"
          args:
            - server
            - /var/minio/data
          ports:
            - containerPort: {{ .Values.filestore.port }}
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: FILE_STORE_SECRET_KEY
                  name: {{ .Release.Name }}-filestore-secret
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: FILE_STORE_ACCESS_KEY
                  name: {{ .Release.Name }}-filestore-secret
          volumeMounts:
            - mountPath:  /var/minio/data
              name: filestore-volume
{{ end }}