apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-api
  labels:
    app: {{ .Release.Name }}-web-api
spec:
  replicas: {{ .Values.webApi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web-api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-maps/web-api-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/web-api-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: web-api
          {{ if .Values.services.webApi }}
          {{ if .Values.services.webApi.image }}
          image: {{ .Values.services.webApi.image }}:3.31.19
          {{ else}}
          image: cryptlex/cryptlex-web-api-enterprise:3.31.19
          {{ end }}
          {{ else}}
          image: cryptlex/cryptlex-web-api-enterprise:3.31.19
          {{ end }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-web-api-config
            - secretRef:
                name: {{ .Release.Name }}-web-api-secret
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "900Mi"
          readinessProbe:
            httpGet:
               path: /v3/status
               port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secret
