apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-api-service
  labels:
    app: {{ .Release.Name }}-web-api-service
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Release.Name }}-web-api
