apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache-service
  labels:
    app: {{ .Release.Name }}-cache-service
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-cache
