{{ if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.certmanager.issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-production-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
       ingress:
         class: nginx
{{ end }}