apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-filestore-secret
type: Opaque
stringData:
  FILE_STORE_ACCESS_KEY: {{ .Values.filestore.accessKey }}
  FILE_STORE_SECRET_KEY: {{ .Values.filestore.secretKey }}