{{ if .Values.ingress.enabled }}
{{- $fullName := include "cryptlex-enterprise.fullname" . -}}

# apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.certmanager.issuer.production }}
    certmanager.k8s.io/issuer: {{ .Release.Name }}-letsencrypt-production
    {{ else}}
    certmanager.k8s.io/issuer: {{ .Release.Name }}-letsencrypt-staging
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.webApiHost }}
        - {{ .Values.ingress.hosts.dashboardHost }}
        {{ if .Values.services.filestore.enabled }}
        - {{ .Values.ingress.hosts.releaseServerHost }}
        {{ end }}
      secretName: {{ printf "%s%s%s" .Release.Name .Values.ingress.hosts.webApiHost .Values.ingress.hosts.dashboardHost | sha256sum | trunc 30}}-tls-secret
  rules:
    - host: {{ .Values.ingress.hosts.webApiHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-web-api-service
              servicePort: 5000
    - host: {{ .Values.ingress.hosts.dashboardHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-dashboard-service
              servicePort: 4200
    {{ if .Values.services.filestore.enabled }}
    - host: {{ .Values.ingress.hosts.releaseServerHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-release-server-service
              servicePort: 3000
    {{ end }}
{{ end }}