{{ if .Values.ingress.enabled }}
{{- $fullName := include "cryptlex-enterprise.fullname" . -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .Values.certmanager.issuer.production }}
    cert-manager.io/issuer: {{ .Release.Name }}-letsencrypt-production
    {{ else}}
    cert-manager.io/issuer: {{ .Release.Name }}-letsencrypt-staging
    {{ end }}
    {{ if .Values.ingress.enableLegacyTls }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA;
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.webApiHost }}
        - {{ .Values.ingress.hosts.dashboardHost }}
        {{ if .Values.services.filestore.enabled }}
        - {{ .Values.ingress.hosts.releaseServerHost }}
        {{ end }}
      secretName: {{ printf "%s%s%s" .Release.Name .Values.ingress.hosts.webApiHost .Values.ingress.hosts.dashboardHost | sha256sum | trunc 30}}-tls-secret
  rules:
    - host: {{ .Values.ingress.hosts.webApiHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-web-api-service
              servicePort: 5000
    - host: {{ .Values.ingress.hosts.dashboardHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-dashboard-service
              servicePort: 4200
    {{ if .Values.services.filestore.enabled }}
    - host: {{ .Values.ingress.hosts.releaseServerHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-release-server-service
              servicePort: 3000
    {{ end }}
{{ end }}