name: Update chart image tags

on:
  repository_dispatch:
    types: [update-helm-chart]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install yq
        run: sudo snap install yq
      
      - name: Update dashboard image tag
        if: ${{ github.event.client_payload.dashboard_tag }}
        run: yq w -i cryptlex/cryptlex-enterprise/values.yaml 'services.dashboard.image.tag' ${{ github.event.client_payload.dashboard_tag }}
      
      - name: Update web api image tag
        if: ${{ github.event.client_payload.web_api_tag }}
        run: yq w -i cryptlex/cryptlex-enterprise/values.yaml 'services.webApi.image.tag' ${{ github.event.client_payload.web_api_tag }}

      - name: Get current chart version
        id: chartVersion
        run: echo "##[set-output name=version;]$(yq r cryptlex/cryptlex-enterprise/Chart.yaml 'version')"

      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.chartVersion.outputs.version }}
      
      - name: Update chart version
        run: |
          yq w -i cryptlex/cryptlex-enterprise/Chart.yaml 'version' ${{ steps.semvers.outputs.patch }}
          yq w -i cryptlex/cryptlex-enterprise/Chart.yaml 'appVersion' ${{ steps.semvers.outputs.patch }}
           
      - name: Commit files
        run: |
          git add ./cryptlex/cryptlex-enterprise/*.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated images" -a | exit 0
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}