name: Update image tags

on:
  repository_dispatch:
    types: [update-helm-chart]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install yq
        run: sudo apt install yq -y
      
      - name: Update dashboard image tag
        if: ${{ github.event.client_payload.dashboard.tag != '' }}
        run: yq w -i cryptlex/cryptlex-enterprise/values.yaml 'services.dashboard.image.tag' ${{ github.event.client_payload.dashboard.tag }}
      
      - name: Update web api image tag
        if: ${{ github.event.client_payload.webApi.tag != '' }}
        run: yq w -i cryptlex/cryptlex-enterprise/values.yaml 'services.webApi.image.tag' ${{ github.event.client_payload.webApi.tag }}

      # - name: Update chart version
      #   run: ./scripts/fetch-resources.sh
           
      - name: Commit and push updates
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
              ./cryptlex/cryptlex-enterprise/Chart.yaml
              ./cryptlex/cryptlex-enterprise/values.yaml
          commit-msg: Updated images
          github-token: ${{ secrets.GITHUB_TOKEN }}